"""Reset Schema with Models Imported

Revision ID: 1558e7f57603
Revises: 
Create Date: 2026-02-19 13:20:19.851387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1558e7f57603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.String(length=50), nullable=False),
    sa.Column('hospital', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=False),
    sa.Column('prediction', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('disease_selected', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('trestbps', sa.Integer(), nullable=True),
    sa.Column('chol', sa.Integer(), nullable=True),
    sa.Column('fbs', sa.Integer(), nullable=True),
    sa.Column('restecg', sa.Integer(), nullable=True),
    sa.Column('thalach', sa.Integer(), nullable=True),
    sa.Column('exang', sa.Integer(), nullable=True),
    sa.Column('oldpeak', sa.Float(), nullable=True),
    sa.Column('slope', sa.Integer(), nullable=True),
    sa.Column('pregnancies', sa.Integer(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('bp', sa.Float(), nullable=True),
    sa.Column('skin_thickness', sa.Float(), nullable=True),
    sa.Column('insulin', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('dpf', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('user')
    op.drop_table('doctor')
    # ### end Alembic commands ###
