"""Add doctor review pipeline

Revision ID: 5f8f7573d0d9
Revises: 1558e7f57603
Create Date: 2026-02-19 15:29:05.313726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8f7573d0d9'
down_revision = '1558e7f57603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('hospital', sa.String(length=200), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_profile_license_number'), ['license_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctor_profile_user_id'), ['user_id'], unique=True)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('patient_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('disease_type', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('report_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_report_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_report_result_id'), ['result_id'], unique=True)

    op.create_table('doctor_review_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['patient_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_review_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_review_request_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_review_request_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_review_request_report_id'), ['report_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('doctor_review_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_review_request_report_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_review_request_patient_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_review_request_doctor_id'))

    op.drop_table('doctor_review_request')
    with op.batch_alter_table('patient_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_report_result_id'))
        batch_op.drop_index(batch_op.f('ix_patient_report_patient_id'))

    op.drop_table('patient_report')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_profile_license_number'))

    op.drop_table('doctor_profile')
    # ### end Alembic commands ###
