"""add probability

Revision ID: 832103b612ec
Revises: 
Create Date: 2026-02-18 23:10:30.287026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832103b612ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probability', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('probability')

    # ### end Alembic commands ###
